//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiComunicacaoFornecedor.ServiceReferenceEstoqueFornecedor {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="xml", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class xml : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApiComunicacaoFornecedor.ServiceReferenceEstoqueFornecedor.Produto produtoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public WebApiComunicacaoFornecedor.ServiceReferenceEstoqueFornecedor.Produto produto {
            get {
                return this.produtoField;
            }
            set {
                if ((object.ReferenceEquals(this.produtoField, value) != true)) {
                    this.produtoField = value;
                    this.RaisePropertyChanged("produto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Produto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Produto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cod_produtoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nom_produtoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string quant_estoqueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string cod_produto {
            get {
                return this.cod_produtoField;
            }
            set {
                if ((object.ReferenceEquals(this.cod_produtoField, value) != true)) {
                    this.cod_produtoField = value;
                    this.RaisePropertyChanged("cod_produto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nom_produto {
            get {
                return this.nom_produtoField;
            }
            set {
                if ((object.ReferenceEquals(this.nom_produtoField, value) != true)) {
                    this.nom_produtoField = value;
                    this.RaisePropertyChanged("nom_produto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string quant_estoque {
            get {
                return this.quant_estoqueField;
            }
            set {
                if ((object.ReferenceEquals(this.quant_estoqueField, value) != true)) {
                    this.quant_estoqueField = value;
                    this.RaisePropertyChanged("quant_estoque");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceEstoqueFornecedor.ProdutosSoap")]
    public interface ProdutosSoap {
        
        // CODEGEN: Generating message contract since element name idProduto from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obterEstoqueProduto", ReplyAction="*")]
        WebApiComunicacaoFornecedor.ServiceReferenceEstoqueFornecedor.obterEstoqueProdutoResponse obterEstoqueProduto(WebApiComunicacaoFornecedor.ServiceReferenceEstoqueFornecedor.obterEstoqueProdutoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obterEstoqueProduto", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApiComunicacaoFornecedor.ServiceReferenceEstoqueFornecedor.obterEstoqueProdutoResponse> obterEstoqueProdutoAsync(WebApiComunicacaoFornecedor.ServiceReferenceEstoqueFornecedor.obterEstoqueProdutoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obterEstoqueProdutoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obterEstoqueProduto", Namespace="http://tempuri.org/", Order=0)]
        public WebApiComunicacaoFornecedor.ServiceReferenceEstoqueFornecedor.obterEstoqueProdutoRequestBody Body;
        
        public obterEstoqueProdutoRequest() {
        }
        
        public obterEstoqueProdutoRequest(WebApiComunicacaoFornecedor.ServiceReferenceEstoqueFornecedor.obterEstoqueProdutoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obterEstoqueProdutoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idProduto;
        
        public obterEstoqueProdutoRequestBody() {
        }
        
        public obterEstoqueProdutoRequestBody(string idProduto) {
            this.idProduto = idProduto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obterEstoqueProdutoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obterEstoqueProdutoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApiComunicacaoFornecedor.ServiceReferenceEstoqueFornecedor.obterEstoqueProdutoResponseBody Body;
        
        public obterEstoqueProdutoResponse() {
        }
        
        public obterEstoqueProdutoResponse(WebApiComunicacaoFornecedor.ServiceReferenceEstoqueFornecedor.obterEstoqueProdutoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obterEstoqueProdutoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public WebApiComunicacaoFornecedor.ServiceReferenceEstoqueFornecedor.xml xml;
        
        public obterEstoqueProdutoResponseBody() {
        }
        
        public obterEstoqueProdutoResponseBody(WebApiComunicacaoFornecedor.ServiceReferenceEstoqueFornecedor.xml xml) {
            this.xml = xml;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProdutosSoapChannel : WebApiComunicacaoFornecedor.ServiceReferenceEstoqueFornecedor.ProdutosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProdutosSoapClient : System.ServiceModel.ClientBase<WebApiComunicacaoFornecedor.ServiceReferenceEstoqueFornecedor.ProdutosSoap>, WebApiComunicacaoFornecedor.ServiceReferenceEstoqueFornecedor.ProdutosSoap {
        
        public ProdutosSoapClient() {
        }
        
        public ProdutosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProdutosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProdutosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProdutosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApiComunicacaoFornecedor.ServiceReferenceEstoqueFornecedor.obterEstoqueProdutoResponse WebApiComunicacaoFornecedor.ServiceReferenceEstoqueFornecedor.ProdutosSoap.obterEstoqueProduto(WebApiComunicacaoFornecedor.ServiceReferenceEstoqueFornecedor.obterEstoqueProdutoRequest request) {
            return base.Channel.obterEstoqueProduto(request);
        }
        
        public WebApiComunicacaoFornecedor.ServiceReferenceEstoqueFornecedor.xml obterEstoqueProduto(string idProduto) {
            WebApiComunicacaoFornecedor.ServiceReferenceEstoqueFornecedor.obterEstoqueProdutoRequest inValue = new WebApiComunicacaoFornecedor.ServiceReferenceEstoqueFornecedor.obterEstoqueProdutoRequest();
            inValue.Body = new WebApiComunicacaoFornecedor.ServiceReferenceEstoqueFornecedor.obterEstoqueProdutoRequestBody();
            inValue.Body.idProduto = idProduto;
            WebApiComunicacaoFornecedor.ServiceReferenceEstoqueFornecedor.obterEstoqueProdutoResponse retVal = ((WebApiComunicacaoFornecedor.ServiceReferenceEstoqueFornecedor.ProdutosSoap)(this)).obterEstoqueProduto(inValue);
            return retVal.Body.xml;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApiComunicacaoFornecedor.ServiceReferenceEstoqueFornecedor.obterEstoqueProdutoResponse> WebApiComunicacaoFornecedor.ServiceReferenceEstoqueFornecedor.ProdutosSoap.obterEstoqueProdutoAsync(WebApiComunicacaoFornecedor.ServiceReferenceEstoqueFornecedor.obterEstoqueProdutoRequest request) {
            return base.Channel.obterEstoqueProdutoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApiComunicacaoFornecedor.ServiceReferenceEstoqueFornecedor.obterEstoqueProdutoResponse> obterEstoqueProdutoAsync(string idProduto) {
            WebApiComunicacaoFornecedor.ServiceReferenceEstoqueFornecedor.obterEstoqueProdutoRequest inValue = new WebApiComunicacaoFornecedor.ServiceReferenceEstoqueFornecedor.obterEstoqueProdutoRequest();
            inValue.Body = new WebApiComunicacaoFornecedor.ServiceReferenceEstoqueFornecedor.obterEstoqueProdutoRequestBody();
            inValue.Body.idProduto = idProduto;
            return ((WebApiComunicacaoFornecedor.ServiceReferenceEstoqueFornecedor.ProdutosSoap)(this)).obterEstoqueProdutoAsync(inValue);
        }
    }
}
